### ISSUE TITLE
scivis Volume valueRange is a FLOAT32_BOX1

### ISSUE THREAD

**Issue by johguenther** [KhronosGroup/ANARI-SDK#11]
yet [anari_test_scenes/scenes/gravity_spheres_volume.cpp:145](https://github.com/KhronosGroup/ANARI-SDK/blob/main/libs/anari_test_scenes/scenes/gravity_spheres_volume.cpp#L145) and [example_device/scene/volume/Volume.cpp:19](https://github.com/KhronosGroup/ANARI-SDK/blob/main/examples/example_device/scene/volume/Volume.cpp#L19) use `FLOAT32_VEC2`

**Comment by jeffamstutz** [comment]
Yes, this is incorrect in the examples -- just needs to be revised to the spec.

**Comment by progschj** [comment]
The initial concern should be resolved by https://github.com/KhronosGroup/ANARI-SDK/commit/81672598a3517a20a99c9ce42c13e71846068b24
