### ISSUE TITLE
ANARIFeatures missing extension ANARI_KHR_STEREO_RENDERING

### ISSUE THREAD

**Issue by griffin28** [KhronosGroup/ANARI-SDK#124]
The **ANARIFeatures** struct is missing extension `ANARI_KHR_STEREO_RENDERING`.

**Comment by progschj** [comment]
This is caused by the api json definitions not having caught up to the current state of the spec yet. Once those are up to date with the spec the feature utility generator will pick them up.

**Comment by jeffamstutz** [comment]
The `v0.7.0` release is in sync with the latest v1.0 spec, including stereo rendering.
