### ISSUE TITLE
Create an offline version for the build

### ISSUE THREAD

**Issue by dimitris64bit** [KhronosGroup/ANARI-SDK#142]
Please make it possible to build the package in cases where no internet access is available. Now one has to copy all the .zip files. Also the pybind11 cloning is not possible.

How can I replace the fetch with a local copy?

THanks

**Comment by jeffamstutz** [comment]
If the .zips that get download are in place, then they won't get fetched again....however, this requires them to have been fetched to begin with!

I'm prepping for the next release on Friday, so I think between now and then I can consolidate things to be able to create an "offline" source zip that I can upload to the release artifacts when it goes live.

I will say that I do recognize the struggle of building without an internet connection -- some people struggle being bothered with building external dependencies, and the system created to make that "easy" then has the internet connection constraint. I'll see what I can do to try and strike a better balance, especially knowing there's at least someone who would prefer to do a purely offline build. Thanks for the feedback!

**Comment by jeffamstutz** [comment]
The latest `v0.7.0` release now uses a central method for fetching dependencies that permits having a pre-populated download cache for use in building without an internet connection. The releases will now always have a "download free" `.zip` that you can use in offline contexts.

Please reopen if you continue to have issues, but I've been able to build with my internet connection turned off now using the official release source zip. Thanks for reporting this!

**Comment by dimitris64bit** [comment]
Thanks a lot! Will check it and come back if I have any issues.
