### ISSUE TITLE
NULL pointer dereference in anariLoadLibrary if ANARI_LIBRARY is not set

### ISSUE THREAD

**Issue by MrROBUST** [KhronosGroup/ANARI-SDK#144]
The `getenv` function will return a NULL pointer if the environment variable is not set on the line:
https://github.com/KhronosGroup/ANARI-SDK/blob/c755452e7851186064b7a841940510f5f40a6cb2/libs/anari/API.cpp#L86
which will be stored in the variable `libraryName` (and the reference `name`) in the line:
https://github.com/KhronosGroup/ANARI-SDK/blob/c755452e7851186064b7a841940510f5f40a6cb2/libs/anari/API.cpp#L93
then it will be used in string concatenation in the line:
https://github.com/KhronosGroup/ANARI-SDK/blob/c755452e7851186064b7a841940510f5f40a6cb2/libs/anari/API.cpp#L104

**Comment by MrROBUST** [comment]
also value of variable `newLibraryFcn` may stay as `nullptr` after `catch` clause and then used as function call in following `return` statement.

**Comment by jeffamstutz** [comment]
This was cleaned up in the latest `v0.7.0` release, thanks for reporting it!
