### ISSUE TITLE
`primitive.index` not used for indexing into `vertex.color`

### ISSUE THREAD

**Issue by stukowski** [KhronosGroup/ANARI-SDK#147]
I am using Helide to render a sub-set of spheres. I've set the geometry's `primitive.index` parameter to an `ARRAY1D` of `UINT32`. Positions and radii turn out correctly (they are obtained from indexing into `vertex.position` and `vertex.radius`) but not the spheres' colors. Their colors seem to be taken from the `vertex.color` array without indexing.

The ANARI spec claims: 

> Each element of `primitive.index` defines one sphere, indexing into the `vertex.*` arrays.

I am wondering whether I am observing a limitation (or bug) of the helide renderer or doing something wrong on the application side.

**Comment by jeffamstutz** [comment]
I think this is a bug in helide -- should be straightforward to fix. I'll close this once it's in, thanks!
