### ISSUE TITLE
Vcpkg port

### ISSUE THREAD

**Issue by acdemiralp** [KhronosGroup/ANARI-SDK#149]
Just a heads up, I have added ANARI to microsoft/vcpkg so its a bit easier to build and use:
https://github.com/microsoft/vcpkg/tree/master/ports/anari
https://github.com/microsoft/vcpkg/pull/33213 

I am currently adding OptiX + VisRTX. Might also do OSPRay and ProRender in the future.

Opening this issue in case you consider adding it to the documentation.

**Comment by jeffamstutz** [comment]
This is great, thank you for doing it! Getting ANARI + backends into package managers is very valuable, and this is a great first step. Once I have a chance to try it for myself, I'll put it in the README and close this issue.

Thanks again!

**Comment by jeffamstutz** [comment]
I included a fix for this in the `v0.7.2` release, thanks again!
