### ISSUE TITLE
Mistake in cornell box scene

### ISSUE THREAD

**Issue by V-Gorash** [KhronosGroup/ANARI-SDK#15]
In cornell box scene (cornell_box.cpp) there's a possible mistake. There's a check of ANARI_KHR_DEVICE_SYNCHRONIZATION feature (line 275), but it looks like that it should check ANARI_KHR_AREA_LIGHTS

**Comment by jeffamstutz** [comment]
Yes, that's correct! I'll add a check that adds a different light if `ANARI_KHR_AREA_LIGHTS` isn't present.

**Comment by jeffamstutz** [comment]
That's a bewildering bug to have written, haha.

**Comment by jeffamstutz** [comment]
Fixed in 0ce0a30.
