### ISSUE TITLE
Mistakes in test scenes

### ISSUE THREAD

**Issue by V-Gorash** [KhronosGroup/ANARI-SDK#18]
Hello. I found some some issues in ANARI test scenes:

1) In textured_cube.cpp, line 99, there's an incorrect subtype name ("texture2d", but correct name in documentation is a "image2D")

2) In random_spheres.cpp there's no release of surface. In line 49 `anari:setParameter` is used instead of `anari:setAndReleaseParameter`. Destructor of surface won't be called because surface have one reference.

3) In file_obj.cpp there's a undocumented parameter using ("vertex.texcoord") (line 139)

**Comment by jeffamstutz** [comment]
Thanks for reporting these! They have been addressed in eef33bc.
