### ISSUE TITLE
Windows cmake 3.21.4 build fails

### ISSUE THREAD

**Issue by kingc8** [KhronosGroup/ANARI-SDK#2]
Hello,

When compiling the Anari SDK on Windows 11 Visual Studio 2019 I get this build error:

`8>Generating Code...
8>Done building project "anari_library_example.vcxproj" -- FAILED.
12>------ Build started: Project: anariTutorialDirectLink, Configuration: Release x64 ------
12>Building Custom Rule C:/Users/Cameron/Downloads/ANARI-SDK/examples/direct_linking/CMakeLists.txt
12>anariTutorialDirectLink.c
12>LINK : fatal error LNK1181: cannot open input file '..\..\Release\anari_library_example.lib'
12>Done building project "anariTutorialDirectLink.vcxproj" -- FAILED.
13>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------
13>Building Custom Rule C:/Users/Cameron/Downloads/ANARI-SDK/CMakeLists.txt
========== Build: 8 succeeded, 5 failed, 0 up-to-date, 0 skipped ==========
`
I attempt to continue the build:

`1>C:\Users\Cameron\Downloads\ANARI-SDK\examples\example_device\scene\bvh/SweepSAHBuilder.h(294,3): error C2059: syntax error: '{'
1>C:\Users\Cameron\Downloads\ANARI-SDK\examples\example_device\scene\bvh/SweepSAHBuilder.h(294,3): error C2143: syntax error: missing ';' before '{'
1>C:\Users\Cameron\Downloads\ANARI-SDK\examples\example_device\scene\bvh/SweepSAHBuilder.h(301,31): warning C4267: '=': conversion from 'size_t' to 'uint32_t', possible loss of data
1>C:\Users\Cameron\Downloads\ANARI-SDK\examples\example_device\scene\volume\../SceneObject.h(84,9): error C3001: 'declare': expected an OpenMP directive name
1>C:\Users\Cameron\Downloads\ANARI-SDK\examples\example_device\scene\volume\../SceneObject.h(88,9): error C3036: 'bbox_extend': invalid operator token in OpenMP 'reduction' clause
1>C:\Users\Cameron\Downloads\ANARI-SDK\examples\example_device\scene\volume\../SceneObject.h(88,1): error C3016: 'i': index variable in OpenMP 'for' statement must have signed integral type
1>Generating Code...
1>Done building project "anari_library_example.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========`

Am I missing prerequisites? I hope this is helpful.

Kind regards,

Cameron

**Comment by kingc8** [comment]
Hi Jefferson,

Thanks very much, commenting that out seems to have improved the compilation on Windows.

This is the remaining result, I have removed the Warnings.

`6>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\simple\anariTutorial.c(13,10): fatal error C1083: Cannot open include file: 'alloca.h': No such file or directory
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\scene\bvh/BVH.h(66,33): error C2338: BVH::Node is too big!
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\scene\bvh/BVH.h(66,33): error C2338: BVH::Node is too big!
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\scene\bvh/BVH.h(66,33): error C2338: BVH::Node is too big!
10>LINK : fatal error LNK1181: cannot open input file '..\..\Release\anari_utilities.lib'
11>LINK : fatal error LNK1181: cannot open input file '..\..\Release\anari_utilities.lib'
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\scene\bvh/BVH.h(66,33): error C2338: BVH::Node is too big!
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\scene\bvh/BVH.h(66,33): error C2338: BVH::Node is too big!
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\scene\bvh/BVH.h(66,33): error C2338: BVH::Node is too big!
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\scene\bvh/BVH.h(66,33): error C2338: BVH::Node is too big!
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\renderer\Renderer.cpp(20,51): error C7555: use of designated initializers requires at least '/std:c++20'
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\scene\bvh/BVH.h(66,33): error C2338: BVH::Node is too big!
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\scene\bvh/BVH.h(66,33): error C2338: BVH::Node is too big!
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\scene\bvh/BVH.h(66,33): error C2338: BVH::Node is too big!
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\scene\bvh/BVH.h(66,33): error C2338: BVH::Node is too big!
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\scene\bvh/BVH.h(66,33): error C2338: BVH::Node is too big!
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\scene\bvh/BVH.h(66,33): error C2338: BVH::Node is too big!
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\scene\bvh/BVH.h(66,33): error C2338: BVH::Node is too big!
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\scene\bvh/BVH.h(66,33): error C2338: BVH::Node is too big!
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\scene\bvh/BVH.h(66,33): error C2338: BVH::Node is too big!
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\scene\bvh/BVH.h(66,33): error C2338: BVH::Node is too big!
12>LINK : fatal error LNK1181: cannot open input file '..\..\Release\anari_library_example.lib'
`
Many thanks and kind regards,

Cameron

**Comment by jeffamstutz** [comment]
I've pushed the OpenMP CMake logic workaround and removed the static assert which was failing (seemed unnecessary). Could you retry latest `main`?

**Comment by kingc8** [comment]
Hi Jefferson,

Redownloaded main and compiled, it's looking better.

`6>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\simple\anariTutorial.c(13,10): fatal error C1083: Cannot open include file: 'alloca.h': No such file or directory
11>LINK : fatal error LNK1181: cannot open input file '..\..\Release\anari_utilities.lib'
10>LINK : fatal error LNK1181: cannot open input file '..\..\Release\anari_utilities.lib'
8>C:\Users\Cameron\Downloads\ANARI-SDK-main\examples\example_device\renderer\Renderer.cpp(20,51): error C7555: use of designated initializers requires at least '/std:c++20'
12>LINK : fatal error LNK1181: cannot open input file '..\..\Release\anari_library_example.lib'

...
8>Done building project "anari_library_example.vcxproj" -- FAILED.
12>------ Build started: Project: anariTutorialDirectLink, Configuration: Release x64 ------
12>Building Custom Rule C:/Users/Cameron/Downloads/ANARI-SDK-main/examples/direct_linking/CMakeLists.txt
12>anariTutorialDirectLink.c
12>LINK : fatal error LNK1181: cannot open input file '..\..\Release\anari_library_example.lib'
12>Done building project "anariTutorialDirectLink.vcxproj" -- FAILED.
13>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------T
13>Building Custom Rule C:/Users/Cameron/Downloads/ANARI-SDK-main/CMakeLists.txt
========== Build: 8 succeeded, 5 failed, 0 up-to-date, 0 skipped ==========`

Thank you for the quick feedback!

Kind regards,,

Cameron

**Comment by jeffamstutz** [comment]
Just pushed an update to just use plain `malloc()` for the `anariTutorial` app...hopefully we are close!

**Comment by kingc8** [comment]
Pulled down a fresh main.
It seems like it's only the memory allocation header that needs a pre-processor statement,

Windows will look for:
#include <malloc.h>
Others:
 #include <alloca.h>

That's the only error left on Windows!

Thank you for your awesome work!

Kind regards,

Cameron

**Comment by kingc8** [comment]
Its better.

13>LINK : fatal error LNK1181: cannot open input file '..\..\Release\anari_utilities.lib'
13>Done building project "anari_library_example.vcxproj" -- FAILED.
17>------ Rebuild All started: Project: anariTutorialDirectLink, Configuration: Release x64 ------
17>Building Custom Rule C:/Users/Cameron/Downloads/ANARI-SDK-main/examples/direct_linking/CMakeLists.txt
17>anariTutorialDirectLink.c
17>LINK : fatal error LNK1181: cannot open input file '..\..\Release\anari_library_example.lib'
17>Done building project "anariTutorialDirectLink.vcxproj" -- FAILED.
18>------ Rebuild All started: Project: ALL_BUILD, Configuration: Release x64 ------
18>Building Custom Rule C:/Users/Cameron/Downloads/ANARI-SDK-main/CMakeLists.txt
19>------ Skipped Rebuild All: Project: INSTALL, Configuration: Release x64 ------
19>Project not selected to build for this solution configuration 
========== Rebuild All: 9 succeeded, 4 failed, 6 skipped ==========

-I appreciate you're tweaking all this from a Linux based codebase.

Many thanks,

Cameron
