### ISSUE TITLE
Anari Python Bindings, Arrays of Arrays

### ISSUE THREAD

**Issue by szellmann** [KhronosGroup/ANARI-SDK#200]
Hi,
I'm trying to use the Python bindings, with an AMR spatial field extension. That extension requires the block data to be specified as a `ANARI_ARRAY1D` of `ANARI_ARRAY1D` (of `ANARI_FLOAT32`). Myself being an absolute Python newbie, and with very little experience with the pyanari bindings, I wonder if someone could give me a pointer how to do this. For reference, some work in progress code that currently fails for me with memory access violations (upon setting those arrays) can be found here in this file:

https://github.com/szellmann/yt/blob/anari/yt/visualization/volume_rendering/anari_volume_rendering.py#L271

Perhaps someone can point me to some example code showing how this is done. I'm currently working off the tutorial as well as the blender plug-in.

**Comment by jeffamstutz** [comment]
@progschj

**Comment by szellmann** [comment]
Indeed, that works! Thank you.

Is there also an example of using Array3D's? I now see the data correctly mapped into the memory of the device, but I just found out the inner arrays are supposed to be 3D not 1D.

**Comment by progschj** [comment]
should be as easy as:
```
bd = anariNewArray3D(device, ffi.from_buffer(blockData[i]), ANARI_FLOAT32, width, height, depth)
```

**Comment by szellmann** [comment]
Awesome thank you. I know these are newbie questions, so thanks for helping me out!

**Comment by szellmann** [comment]
This helped me. So I think I can close the issue. Thanks again!

**Comment by szellmann** [comment]
@progschj 
Thanks for the help so far. I'm reopening the issue as I'm still struggling with creating 3D arrays, and at this point am not sure if this is a bug in Anari (or the Python bindings).

The issue I observe is that when initializing arrays of type `ANARI_ARRAY3D`, the data arriving on the device has only the first row of the first slice set.

I'm attaching a minimal reproducer (with a `structuredRegular` volume). Could you perhaps take a look if I'm doing this right? In that code, note there are two variants, one where the data comes from a flat 1D array (lines 31ff), and a second variant with the data coming from a 3D array (lines 31ff).

In both cases, note that I set all the data to `0.1`, but the data values I print in the device are:
```
0.1 0.1 
0 0 

0 0 
0 0
```
So only row0 of slice0 is set. I might just be doing this wrong. Or there's a bug somewhere, but I'm not sure.

[pyanari-array3d-reproducer.txt](https://github.com/KhronosGroup/ANARI-SDK/files/15081673/pyanari-array3d-reproducer.txt)

**Comment by progschj** [comment]
Whoops, the flat array version should work but there was a copy paste error I just tried to fix here:  https://github.com/KhronosGroup/ANARI-SDK/commit/cb0d88ec5d9eec93cf7cfa1e072a9e88ac21a587

**Comment by szellmann** [comment]
I pulled the commit, tested and can confirm that it fixes my issue (both in the reproducer with both variants, as well as in the AMR case with the nested grids in YT). Thanks for the quick response!
