### ISSUE TITLE
Build error when BUILD_TESTING is false but BUILD_EXAMPLES is true

### ISSUE THREAD

**Issue by player1537** [KhronosGroup/ANARI-SDK#22]
#16 added support for only including the glm dependency when BUILD_TESTING is on, but I believe it also needs to be enabled when BUILD_EXAMPLES is on.

I believe that in `external/CMakeLists.txt` then the if statement for whether to download glm should read:

```cmake
if (BUILD_TESTING OR BUILD_EXAMPLES)
```

---

I've tested this by verifying that the following succeeds:

```console
$ cmake -DBUILD_TESTING:BOOL=ON -DBUILD_EXAMPLES:BOOL=ON
```

The following fails:

```console
$ cmake -DBUILD_TESTING:BOOL=OFF -DBUILD_EXAMPLES:BOOL=ON
```

And that command succeeds after changing `external/CMakeLists.txt`:

```diff
-if (BUILD_TESTING)
+if (BUILD_TESTING OR BUILD_EXAMPLES)
```

**Comment by jeffamstutz** [comment]
This is now fixed on `main`, thanks!
