### ISSUE TITLE
anari_test_scene: T convert() has missing return value

### ISSUE THREAD

**Issue by ingowald** [KhronosGroup/ANARI-SDK#242]
lines 218++:
 T convert(float x) {
    if(std::is_same<T, float>::value) {
      return x;
    } else if(std::is_integral<T>::value) {
      return (T)(double(x)*std::numeric_limits<T>::max());
    }
  }
}; 

has no fallback return value if both ifs were false.

**Comment by jeffamstutz** [comment]
This is fixed in the latest `v0.11.0` release.
