### ISSUE TITLE
Building helide device fails for CMake 3.18

### ISSUE THREAD

**Issue by griffin28** [KhronosGroup/ANARI-SDK#79]
When building the latest ANARI SDK with `BUILD_HELIDE_DEVICE:BOOL=ON` and using **CMake 3.18** I get the error below with `curl` (which does support the required protocols and was manually tested and successfully downloaded the **embree** file).

However, when using **CMake 3.25.1** the ANARI SDK builds successfully. VisIt's automated build scripts currently use **CMake 3.18** and are generally several CMake releases behind the current. 

![embree_error](https://user-images.githubusercontent.com/26772741/209854892-71abf032-19d3-45f8-aa5b-b9cf34ba4105.png)

**Comment by jeffamstutz** [comment]
There's now an official source release that contains all the pre-downloaded versions of all the dependencies with it. My hope is that this issue can be worked around by using that source zip release, or at least the new infrastructure for fetching sources by CMake doesn't trigger the same problem you experienced (i.e. CPM is no longer used to get Embree).

Please reopen if you continue to have issues, but this may actually just be an issue with CMake itself. Thanks!
