### ISSUE TITLE
ANARI ERROR: 'environment' library selected but ANARI_LIBRARY is not set

### ISSUE THREAD

**Issue by kingc8** [KhronosGroup/ANARI-SDK#9]
Hello,

The Windows build completes fully. But when I run the 'viewer.exe' or 'anari_regression_tests.exe'

`ANARI ERROR: 'environment' library selected but ANARI_LIBRARY is not set`

Is this something missing from the environment variables?

Kind regards,

Cameron

**Comment by johguenther** [comment]
ANARI applications like `viewer` can use different ANARI backends. A special library `environment` allows you to specify which backend is used based on the environment variable `ANARI_LIBRARY`. So, either
- set it to e.g. `example` to select the example backend (via command line like `ANARI_LIBRARY=example ./viewer.exe`, or in the Windows settings)
- or hardcode it by replacing `environment` to `example` here: https://github.com/KhronosGroup/ANARI-SDK/blob/main/examples/viewer/main.cpp#L10

**Comment by kingc8** [comment]
Perfect, thank you.
