### ISSUE TITLE
Building GL Viewer on macOS fails due to missing GLES

### ISSUE THREAD

**Issue by szellmann** [KhronosGroup/ANARI-SDK#98]
Compiling on macOS fails, when building only the GL viewer but not the GLES viewer.

This can be reproduced with a fresh checkout of the recent `main` branch (commit f5ae12acf89830cb1099394202e81cc2dc059b54) and configuring with:

`cmake .. -DBUILD_VIEWER=ON -DBUILD_GLES_VIEWER=OFF`

On `make`, the compiler produces the following error message:

```/Users/stefan/ANARI-SDK/build-test/imgui/backends/imgui_impl_opengl3.cpp:93:29: warning: 'TARGET_OS_IOS' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]
#if (defined(__APPLE__) && (TARGET_OS_IOS || TARGET_OS_TV))
                            ^
/Users/stefan/ANARI-SDK/build-test/imgui/backends/imgui_impl_opengl3.cpp:93:46: warning: 'TARGET_OS_TV' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]
#if (defined(__APPLE__) && (TARGET_OS_IOS || TARGET_OS_TV))
                                             ^
/Users/stefan/ANARI-SDK/build-test/imgui/backends/imgui_impl_opengl3.cpp:96:10: fatal error: 'GLES3/gl3.h' file not found
#include <GLES3/gl3.h>          // Use GL ES 3
         ^~~~~~~~~~~~~
2 warnings and 1 error generated.
make[2]: *** [external/CMakeFiles/imgui_glfw_gles2.dir/__/imgui/backends/imgui_impl_opengl3.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

My compiler is `Apple clang version 13.1.6 (clang-1316.0.21.2.5)`. I'm on macOS 12.5.1.

`git-bisect` suggests that the regression was introduced by this commit: 6991cbfb0d7513ebfa500f30082530d02ac38424

**Comment by progschj** [comment]
This should be fixed in #99

**Comment by jeffamstutz** [comment]
I can confirm that this works on my Macbook.

**Comment by szellmann** [comment]
Yes, fixed for me, too.
